apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "You need to provide a value for .Values.app" .Values.app}}
  namespace: "default"
spec:
  replicas: {{.Values.mcp.replicas}}
  selector:
    matchLabels:
      app: {{.Values.app}}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{.Values.app}}
    spec:
      serviceAccountName: {{.Values.app}}sa
      containers:
      - image: "{{.Values.mcp.imageName}}:{{.Values.mcp.imageVersion}}"
        imagePullPolicy: Always
        name: {{.Values.app}}
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: AWS_REGION
          value: {{ required "You need to provide a value for .Values.region" .Values.region}}
        - name: PRODUCT_CODE
          value: {{required "You need a AWS Marketplace product_code to test this sample application" .Values.productCode}}
        - name: PRODUCT_VERSION
          value: {{.Values.mcp.imageVersion}}
        - name: DIMENSIONS_TABLE
          value: {{.Values.app}}DimensionsTable
