apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: {{.Values.app}}
    annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
    labels:
        app: {{.Values.app}}
spec:
    rules:
    - http:
        paths:
        - path: /*
          backend:
            serviceName: {{.Values.app}}
            servicePort: 80